fix spacing

diff --git a/.github/workflows/build-azure-function.yml b/.github/workflows/build-azure-function.yml
--- a/.github/workflows/build-azure-function.yml
+++ b/.github/workflows/build-azure-function.yml
@@ -15,6 +15,8 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+    env:
+      AZURE_CONFIG_DIR: ${{ runner.temp }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -52,12 +54,10 @@ jobs:
         run: |
           secret=$(az keyvault secret show --vault-name "${{ secrets.AZURE_KEYVAULT_NAME }}" --name "apiKey-Stripe" --query value -o tsv)
           if [ -z "$secret" ]; then
-            echo "Could not find Key Vault secret 'apiKey-Stripe' in vault ${ { secrets.AZURE_KEYVAULT_NAME } }" >&2
+            echo "Could not find Key Vault secret 'apiKey-Stripe' in vault ${{ secrets.AZURE_KEYVAULT_NAME }}" >&2
             exit 1
           fi
           echo "STRIPE_API_KEY=$secret" >> $GITHUB_ENV
-        env:
-          AZURE_CONFIG_DIR: ${{ runner.temp }}
 
       - name: Integration Tests
         if: >
